---
name: Publish to RubyGems and Bonsai

on:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-20.04

    steps:

      - name: Clone repository
        uses: actions/checkout@v3

      - name: Clone sensu/sensu-go-bonsai-asset
        uses: actions/checkout@v3
        with:
          repository: sensu/sensu-go-bonsai-asset
          path: bonsai

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.4'

      - name: Setup RubyGems credentials
        run: |
          apt update
          apt install libpq-dev
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}

      - run: bundle exec rake quick

      - run: gem build sensu-plugins-postgres.gemspec

      - run: gem install sensu-plugins-postgres-*.gem

      - name: Publish to RubyGems
        run: gem push sensu-plugins-postgres-*.gem

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Publish to Bonsai
        run: bonsai/ruby-runtime/build-ruby-plugin-assets.sh sensu-plugins-postgres-mrtrotl ${REPO} ${REF} ${VERSION}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          REF: ${{ github.ref }}
          VERSION: ${{ steps.get_version.outputs.VERSION }}

